name: ✨ Feature Request
description: Suggest an idea or improvement for the ASUSTOR package
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request
        
        Thanks for suggesting an improvement! Please fill out the information below.

  - type: checkboxes
    attributes:
      label: ✅ Pre-flight Checklist
      options:
        - label: I have searched existing issues for similar requests
          required: true

  - type: textarea
    attributes:
      label: 🤔 Problem to Solve
      description: |
        What problem does this feature solve?
        A clear description of the pain point.
      placeholder: |
        It's currently difficult to...
        I often need to manually...
    validations:
      required: true

  - type: textarea
    attributes:
      label: 💡 Proposed Solution
      description: |
        Describe the solution you'd like.
        Be as specific as possible.
      placeholder: |
        Add an option to...
        Create a new script that...
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🔄 Alternatives Considered
      description: |
        Have you considered any alternative solutions or workarounds?
      placeholder: |
        I tried to work around this by...
        Another option could be...

  - type: dropdown
    attributes:
      label: 📊 Priority
      description: How important is this feature to you?
      options:
        - 🟢 Nice to have
        - 🟡 Would improve my workflow
        - 🔴 Critical for my use case

  - type: textarea
    attributes:
      label: 📎 Additional Context
      description: |
        Add any other context, mockups, or examples.
