#!/bin/sh
# Cloudflare DNS Challenge configuration helper for Runtipi on ASUSTOR
# This script helps configure Traefik with Cloudflare for wildcard SSL certificates
set -eu -o pipefail

runTipiPath="/share/Docker/RunTipi"
TRAEFIK_DIR="$runTipiPath/traefik"
USER_CONFIG_DIR="$runTipiPath/user-config"
log="/tmp/runtipi-cloudflare.txt"

echo "☁️  Cloudflare Configuration Helper for Runtipi" > "$log"
echo "================================================" >> "$log"

usage() {
  echo "Usage: $0 [OPTIONS]"
  echo ""
  echo "This script configures Runtipi/Traefik to use Cloudflare for:"
  echo "  - Wildcard SSL certificates via Let's Encrypt"
  echo "  - Automatic DNS challenge validation"
  echo ""
  echo "Options:"
  echo "  -e, --email EMAIL         Let's Encrypt email address"
  echo "  -t, --token TOKEN         Cloudflare API Token (DNS:Edit permissions)"
  echo "  -d, --domain DOMAIN       Your domain (e.g., example.com)"
  echo "  --show-config             Show current Traefik configuration"
  echo "  --remove                  Remove Cloudflare configuration"
  echo "  -h, --help                Show this help"
  echo ""
  echo "Cloudflare API Token setup:"
  echo "  1. Go to https://dash.cloudflare.com/profile/api-tokens"
  echo "  2. Create token with 'Zone:DNS:Edit' permission"
  echo "  3. Select your zone (domain)"
  echo ""
  echo "Example:"
  echo "  $0 -e user@example.com -t cf_xxxxxx -d example.com"
  exit 0
}

show_config() {
  echo "📋 Current Traefik Configuration:" >> "$log"
  if [ -f "$TRAEFIK_DIR/traefik.yml" ]; then
    cat "$TRAEFIK_DIR/traefik.yml" >> "$log"
  else
    echo "  No custom traefik.yml found" >> "$log"
  fi
  
  if [ -f "$USER_CONFIG_DIR/tipi-compose.yml" ]; then
    echo "" >> "$log"
    echo "📋 User Compose Override:" >> "$log"
    cat "$USER_CONFIG_DIR/tipi-compose.yml" >> "$log"
  fi
  
  cat "$log"
  exit 0
}

remove_config() {
  echo "🗑️  Removing Cloudflare configuration..." >> "$log"
  [ -f "$TRAEFIK_DIR/traefik.yml.cloudflare" ] && rm -f "$TRAEFIK_DIR/traefik.yml.cloudflare"
  [ -f "$USER_CONFIG_DIR/tipi-compose.yml.cloudflare" ] && rm -f "$USER_CONFIG_DIR/tipi-compose.yml.cloudflare"
  echo "✅ Cloudflare configuration removed" >> "$log"
  echo "⚠️  Remember to set PERSIST_TRAEFIK_CONFIG=false in .env" >> "$log"
  cat "$log"
  exit 0
}

# Parse arguments
EMAIL=""
CF_TOKEN=""
DOMAIN=""
while [ $# -gt 0 ]; do
  case "$1" in
    -e|--email) EMAIL="$2"; shift 2;;
    -t|--token) CF_TOKEN="$2"; shift 2;;
    -d|--domain) DOMAIN="$2"; shift 2;;
    --show-config) show_config;;
    --remove) remove_config;;
    -h|--help) usage;;
    *) echo "Unknown option: $1"; usage;;
  esac
done

# Validate inputs
if [ -z "$EMAIL" ] || [ -z "$CF_TOKEN" ] || [ -z "$DOMAIN" ]; then
  echo "❌ Missing required parameters. Use -h for help." | tee -a "$log"
  exit 1
fi

echo "📧 Email: $EMAIL" >> "$log"
echo "🌐 Domain: $DOMAIN" >> "$log"
echo "🔑 Token: ${CF_TOKEN%${CF_TOKEN#????}}****" >> "$log"

# Create directories
mkdir -p "$TRAEFIK_DIR" "$USER_CONFIG_DIR"

# Create custom traefik.yml with Cloudflare DNS challenge
echo "📝 Creating Traefik configuration..." >> "$log"
cat > "$TRAEFIK_DIR/traefik.yml" << EOF
# Traefik configuration for Runtipi with Cloudflare DNS Challenge
# Generated by cloudflare-setup.sh on $(date)

api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: cloudflare
        domains:
          - main: "$DOMAIN"
            sans:
              - "*.$DOMAIN"

certificatesResolvers:
  cloudflare:
    acme:
      email: "$EMAIL"
      storage: /shared/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
        delayBeforeCheck: 90

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
  file:
    directory: /shared/dynamic
    watch: true

log:
  level: INFO
  filePath: /shared/logs/traefik.log

accessLog:
  filePath: /shared/logs/access.log
  bufferingSize: 100
EOF

echo "✓ Created traefik.yml" >> "$log"

# Create user-config/tipi-compose.yml to inject CF_DNS_API_TOKEN
echo "📝 Creating compose override for Cloudflare token..." >> "$log"
cat > "$USER_CONFIG_DIR/tipi-compose.yml" << EOF
# Cloudflare environment for Traefik
# Generated by cloudflare-setup.sh on $(date)

services:
  runtipi-reverse-proxy:
    environment:
      - CF_DNS_API_TOKEN=$CF_TOKEN
EOF

echo "✓ Created tipi-compose.yml" >> "$log"

# Update .env to persist Traefik config
if [ -f "$runTipiPath/.env" ]; then
  if grep -q "^PERSIST_TRAEFIK_CONFIG=" "$runTipiPath/.env"; then
    sed -i "s|^PERSIST_TRAEFIK_CONFIG=.*|PERSIST_TRAEFIK_CONFIG=true|" "$runTipiPath/.env"
  else
    echo "PERSIST_TRAEFIK_CONFIG=true" >> "$runTipiPath/.env"
  fi
  echo "✓ Set PERSIST_TRAEFIK_CONFIG=true in .env" >> "$log"
fi

# Create acme.json with proper permissions
if [ ! -f "$TRAEFIK_DIR/acme.json" ]; then
  touch "$TRAEFIK_DIR/acme.json"
  chmod 600 "$TRAEFIK_DIR/acme.json"
  echo "✓ Created acme.json (chmod 600)" >> "$log"
fi

echo "" >> "$log"
echo "🎉 Cloudflare configuration completed!" >> "$log"
echo "" >> "$log"
echo "Next steps:" >> "$log"
echo "  1. Restart Runtipi: runtipi-cli restart" >> "$log"
echo "  2. Check logs: tail -f $TRAEFIK_DIR/logs/traefik.log" >> "$log"
echo "  3. Access dashboard: https://$DOMAIN:8080" >> "$log"
echo "" >> "$log"
echo "⚠️  DNS Propagation may take 2-5 minutes" >> "$log"
echo "⚠️  First certificate request may take up to 5 minutes" >> "$log"

cat "$log"
exit 0
